//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Joe/GameStateControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameStateControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameStateControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameStateControls"",
    ""maps"": [
        {
            ""name"": ""StateControlActions"",
            ""id"": ""b697271f-61fd-4909-9adf-d134db472773"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""0e79c4ed-be85-4058-9146-65aa34f67be8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c41370d5-529a-488f-ac5b-626a8e504b71"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50893e52-088b-470b-95c2-d6f6b0f9f340"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // StateControlActions
        m_StateControlActions = asset.FindActionMap("StateControlActions", throwIfNotFound: true);
        m_StateControlActions_Pause = m_StateControlActions.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // StateControlActions
    private readonly InputActionMap m_StateControlActions;
    private IStateControlActionsActions m_StateControlActionsActionsCallbackInterface;
    private readonly InputAction m_StateControlActions_Pause;
    public struct StateControlActionsActions
    {
        private @GameStateControls m_Wrapper;
        public StateControlActionsActions(@GameStateControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_StateControlActions_Pause;
        public InputActionMap Get() { return m_Wrapper.m_StateControlActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StateControlActionsActions set) { return set.Get(); }
        public void SetCallbacks(IStateControlActionsActions instance)
        {
            if (m_Wrapper.m_StateControlActionsActionsCallbackInterface != null)
            {
                @Pause.started -= m_Wrapper.m_StateControlActionsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_StateControlActionsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_StateControlActionsActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_StateControlActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public StateControlActionsActions @StateControlActions => new StateControlActionsActions(this);
    public interface IStateControlActionsActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
